trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- powershell: |
    Write-Host "===== JAVA ENVIRONMENT ====="

    Write-Host "JAVA_HOME:"
    Write-Host $env:JAVA_HOME

    Write-Host "JAVA:"
    where.exe java
    java -version

    Write-Host "JAVAC:"
    where.exe javac
    javac -version

    Write-Host "===== MAVEN ====="
    where.exe mvn
    mvn -version

    Write-Host "===== ALL JAVA INSTALLATIONS ====="
    Get-ChildItem "C:\hostedtoolcache\windows\Java" -Directory -Recurse |
      Select-Object -ExpandProperty FullName

  displayName: 'DIAGNOSE JAVA'
